### PR TITLE
[TECHNICAL-SUPPORT] LPS-57175 Knowledge Base Article portlet: select article pop-up does not show the folder structure

### PR DESCRIPTION
**Pull request by IstvanD**
Hey @adolfopa 

This modification enables the user to browse the folder structure when selecting a KBArticle to display in the Knowledge Base Article portlet configuration.

I used the the code in the Knowledge Base Display portlet as a sample.

This cannot be currently tested on master because of a javascript error, so I prepared the same solution on top of the ee-6.2.x branch for testing:
https://github.com/IstvanD/liferay-plugins-ee/tree/LPS-57175-ee-6.2.x

Could you please take a look at it?

Thanks,
István

### CODE REVIEW

**Comment by adolfopa** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by IstvanD** [comment]
Hey @adolfopa 

I just changed the message key from select-parent to article.
https://github.com/IstvanD/liferay-plugins/commit/bb41b7bcaf38ab10c0ea48891d4b417a263ce147#diff-f06cd0f80358c9a1113dbd3f52b07908R127

Cheers,
István

**Comment by adolfopa** [comment]
@IstvanD I'm in the middle of moving some components into OSGi modules, so it may take me a while to review this pull. I'll try to review and push it tomorrow.

Sorry for the trouble!

**Comment by IstvanD** [comment]
Hi @adolfopa 

No problem.
Thanks for notifying me!

**Comment by IstvanD** [comment]
Hi @adolfopa

I was just wondering if you had time to deal with this pull?

Thanks,
István

**Comment by adolfopa** [comment]
Sorry @IstvanD, but I didn't get the time. We're pushing very hard to extract as much as possible into OSGi modules before the end of the week (c. freeze); We're very close, so I promise I'll review and send it this week. 

If there's something that makes the PR important for you (e.g. customer complaint), I'll prioritize it.

Sorry :-(

**Comment by IstvanD** [comment]
Hi @adolfopa 

Thanks for the reply.
Needless to say, I understand that you are under heavy load.

Is there maybe another reviewer who is a little bit less occupied and can take a look at it sooner?

Because this is a customer issue which is overdue since the beginning of this month, it would be important to deliver the solution in a timely manner.

Thanks,
István

**Comment by lipusz** [comment]
Created https://issues.liferay.com/browse/LPP-17589 to track temp. release.

**Comment by lipusz** [comment]
Released on the ticket.

**Comment by adolfopa** [comment]
Pull request submitted to https://github.com/sergiogonzalez/liferay-plugins/pull/283. [See changes here.](https://github.com/adolfopa/liferay-plugins/compare/2d74759~3...2d74759) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by lipusz** [comment]
Hi István @IstvanD,

Please, make sure you apply the final changes on the temporary plugin
release branch or backport it to ee-6.2.10 in order to be release an
up-to-date version to the Subscriber as soon as it gets merged to master.

Thx,
Tibor

On Fri, Jul 31, 2015 at 3:00 PM, Adolfo Pérez Álvarez <
notifications@github.com> wrote:

> Closed #27 <https://github.com/adolfopa/liferay-plugins/pull/27>.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/adolfopa/liferay-plugins/pull/27#event-370477898>.
>



-- 

*Tibor LIPUSZ*

Senior Software Engineer @ TS
Security SME, Subscription Services & Release, Global


*Liferay Hungary Kft.* | H-1138 Budapest, Madarász Viktor u. 47. a-b.,
Hungary

*Visit Us: **www.liferay.com <http://www.liferay.com/>**  |  Like Us:
**facebook.com/liferay
<http://facebook.com/liferay>**  |  Follow Us: twitter.com/liferay
<http://twitter.com/liferay>*


* <http://twitter.com/liferay>*

<http://www.liferay.com>

**Comment by IstvanD** [comment]
Hi @lipusz 

I will, thanks for the reminder.

**Comment by adolfopa** [comment]
Pull request submitted to https://github.com/sergiogonzalez/liferay-plugins/pull/284. [See changes here.](https://github.com/adolfopa/liferay-plugins/compare/9eef5ad~3...9eef5ad) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
