### PR TITLE
LPS-59957

### PR DESCRIPTION
**Pull request by hhuijser**

### CODE REVIEW

**Comment by adolfopa** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by adolfopa** [comment]
@bejondshao @hhuijser The `word-break` property is pretty new (CSS3), so we need to find a solution/workaround for older browsers. Tomorrow @marcoscv-work and I will work on this; we'll CC you guys in the PR.

Thanks a lot!

**Comment by bejondshao** [comment]
hi adolfopa,

I searched there are so many css files uses "word-break". So I did this for kb-title. If there's anything better, please go ahead.

Thanks

**Comment by adolfopa** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-plugins/pull/5014. <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by adolfopa** [comment]
@bejondshao I've sent your PR as is to Brian, as there seems to be no other way to get that same effect.

Thanks!

**Pull request closed without merging**
