### PR TITLE
LPS-63722 Build Services

### PR DESCRIPTION
**Pull request by sergiogonzalez**

### CODE REVIEW

**Comment by sergiogonzalez** [comment]
cc/ @topolik

**Comment by topolik** [comment]
Perfect, thanks @sergiogonzalez

**Comment by adolfopa** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by topolik** [comment]
Guys, I managed to fix it.

I hope your changes here are not necessary anymore.

Please see https://github.com/brianchandotcom/liferay-portal/pull/36729

**Comment by adolfopa** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-plugins/pull/5194. <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
